#!/usr/bin/env bash
set -euo pipefail

# HA add-on base provides bashio
# shellcheck disable=SC1091
source /usr/lib/bashio/bashio.sh

log_info() { bashio::log.info "$1"; }
log_warn() { bashio::log.warning "$1"; }

PERSIST_BASE="/share/gmod"
SERVER_DIR="${PERSIST_BASE}/server"
GMOD_DIR="${SERVER_DIR}/garrysmod"
CFG_DIR="${GMOD_DIR}/cfg"
SERVER_CFG="${CFG_DIR}/server.cfg"
LOG_DIR="${GMOD_DIR}/logs"

STEAMCMD="/opt/steamcmd/steamcmd.sh"
APP_ID="4020"

STEAM_VALIDATE="$(bashio::config 'steamcmd_validate')"
AUTO_UPDATE="$(bashio::config 'auto_update_on_start')"

HOSTNAME="$(bashio::config 'hostname')"
MAXPLAYERS="$(bashio::config 'maxplayers')"
SV_LAN="$(bashio::config 'sv_lan')"
SV_PASSWORD="$(bashio::config 'sv_password')"
RCON_PASSWORD="$(bashio::config 'rcon_password')"

MAP="$(bashio::config 'map')"
GAMEMODE="$(bashio::config 'gamemode')"

PORT="$(bashio::config 'port')"
CLIENTPORT="$(bashio::config 'clientport')"
RCON_PORT="27016"
TICKRATE="$(bashio::config 'tickrate')"

WORKSHOP_COLLECTION="$(bashio::config 'workshop_collection_id')"
WORKSHOP_AUTHKEY="$(bashio::config 'workshop_authkey')"

GENERATE_CFG="$(bashio::config 'generate_server_cfg_on_start')"
AUTO_RESTART="$(bashio::config 'auto_restart_on_crash')"
RESTART_DELAY="$(bashio::config 'restart_delay_seconds')"

EXTRA_ARGS="$(bashio::config 'extra_args')"

mkdir -p "${SERVER_DIR}" "${CFG_DIR}" "${LOG_DIR}"

if [[ "${AUTO_UPDATE}" == "true" ]] || [[ ! -x "${SERVER_DIR}/srcds_run" ]]; then
  log_info "Installing/updating Garry's Mod server via SteamCMD ..."
  VALIDATE_FLAG=""
  if [[ "${STEAM_VALIDATE}" == "true" ]]; then
    VALIDATE_FLAG="validate"
  fi

  chown -R steam:steam "${PERSIST_BASE}" || true
  su -s /bin/bash -c ""${STEAMCMD}" +force_install_dir "${SERVER_DIR}" +login anonymous +app_update ${APP_ID} ${VALIDATE_FLAG} +quit" steam
  log_info "SteamCMD update finished."
else
  log_info "Auto update disabled and server binaries exist — skipping SteamCMD."
fi

generate_server_cfg() {
  log_info "Generating server.cfg (generate_server_cfg_on_start=true) ..."
  cat > "${SERVER_CFG}" <<EOF
// Generated by Home Assistant add-on (gmod_steamcmd_server)
// This file will be overwritten on each start while generate_server_cfg_on_start=true

hostname "${HOSTNAME}"
sv_lan ${SV_LAN}
sv_password "${SV_PASSWORD}"
rcon_password "${RCON_PASSWORD}"
maxplayers "${MAXPLAYERS}"

sv_region 3
sv_allowcslua 0
EOF

  if [[ -n "${WORKSHOP_COLLECTION}" ]]; then
    echo "host_workshop_collection ${WORKSHOP_COLLECTION}" >> "${SERVER_CFG}"
  fi
  if [[ -n "${WORKSHOP_AUTHKEY}" ]]; then
    echo "// NOTE: workshop_authkey is passed via command line (-authkey)" >> "${SERVER_CFG}"
  fi
}

if [[ "${GENERATE_CFG}" == "true" ]]; then
  generate_server_cfg
else
  log_info "generate_server_cfg_on_start=false -> leaving server.cfg untouched."
fi

build_start_cmd() {
  CMD=( "${SERVER_DIR}/srcds_run" -game garrysmod +map "${MAP}" +gamemode "${GAMEMODE}" +maxplayers "${MAXPLAYERS}" -port "${PORT}" +clientport "${CLIENTPORT}" +rcon_port "${RCON_PORT}" )

  if [[ "${TICKRATE}" -gt 0 ]]; then
    CMD+=( -tickrate "${TICKRATE}" )
  fi
  if [[ -n "${WORKSHOP_COLLECTION}" ]]; then
    CMD+=( +host_workshop_collection "${WORKSHOP_COLLECTION}" )
  fi
  if [[ -n "${WORKSHOP_AUTHKEY}" ]]; then
    CMD+=( -authkey "${WORKSHOP_AUTHKEY}" )
  fi
  if [[ -n "${EXTRA_ARGS}" ]]; then
    # shellcheck disable=SC2206
    EXTRA_ARR=( ${EXTRA_ARGS} )
    CMD+=( "${EXTRA_ARR[@]}" )
  fi

  printf '%q ' "${CMD[@]}"
}

START_CMD="$(build_start_cmd)"

cd "${SERVER_DIR}"

while true; do
  log_info "Starting Garry's Mod server..."
  # Using bash -lc so quoting from printf %q works
  bash -lc "${START_CMD}"

  EXIT_CODE=$?
  log_warn "Server stopped with exit code ${EXIT_CODE}"

  if [[ "${AUTO_RESTART}" != "true" ]]; then
    log_info "Auto restart disabled -> exiting container."
    exit ${EXIT_CODE}
  fi

  log_warn "Restarting server in ${RESTART_DELAY}s..."
  sleep "${RESTART_DELAY}"
done
